[package]
name = "perfprofile"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ksni = "0.2.0"
notify = "5.0.0"
notify-rust = "4.5.10"
